### ISSUE TITLE
Rule documentation

### ISSUE THREAD

**Issue by RinkAttendant6** [dgraham/eslint-plugin-jquery#10]
It would be nice to have some documentation on what each rule enforces, instead of checking all the files inside the `tests/` directory.

A one-line description would suffice, for example, "Disallow use of `$.trim`".
Even better would be examples of incorrect and correct code (ideally showing equivalent versions on how to correct the error).

**Comment by dgraham** [comment]
I prefer to rely on the thorough documentation at [Mozilla Developer Network](https://developer.mozilla.org/en-US/), for the native web platform API, and [jQuery API](http://api.jquery.com) so we don't need to duplicate it here.

When a lint rule is violated, it prints a message like `Prefer addEventListener to $.bind`. Searching for [mdn addEventListener](https://duckduckgo.com/?q=mdn+addeventlistener) and [jquery bind](https://duckduckgo.com/?q=jquery+bind) finds great documentation.
