### ISSUE TITLE
Library makes no distinction utilities and traversal methods with the same name

### ISSUE THREAD

**Issue by edg2s** [dgraham/eslint-plugin-jquery#29]
There are two separate methods called 'each' with different documentation pages:
* https://api.jquery.com/jquery.each/
* https://api.jquery.com/each/

The same is true of 'map':
* https://api.jquery.com/jQuery.map/
* http://api.jquery.com/map/

**Comment by dgraham** [comment]
Right, a single rule covers both cases so all jQuery iteration is deprecated together and can be replaced with native loops and maps.
