### ISSUE TITLE
inconsistent jquery/no-read

### ISSUE THREAD

**Issue by Berkmann18** [dgraham/eslint-plugin-jquery#35]
The rule catches `$(function () { /* ... */ })` but when I change the function into an arrow function like `$(() => { /* ... */ })` it doesn't behave the same way even tho it's technically the same code.
Is it a bug or was that intended?

**Comment by edg2s** [comment]
We fixed this in wikimedia/eslint-plugin-no-jquery/pull/83 if you'd like to port that fix over.
