### ISSUE TITLE
Improve rule for $.toggle

### ISSUE THREAD

**Issue by KovalenkoStas** [dgraham/eslint-plugin-jquery#37]
On our project we usually prepend DOM related variables with double dollar sign "$$" for better readability and searchability. But in that case this "no-jquery" plugin show error for *toggle* method of *classList*.
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#Methods
Something like this:
```
$$container.classList.toggle( SOME_CLASS );
```
and in console we have an error that toggle not allowed, but it is native JS method of *classList* property of DOM element.

I think it would be nice to improve the plugin to not detect *classList.toggle()* as jQuery.

Also I might try to fix it by myself with the help of some core devs :)

Thank you in advance!

**Comment by KovalenkoStas** [comment]
Hello @dgraham, @brendo, @mislav !

Can you please look into it when will have some time.

Thanks!

**Comment by edg2s** [comment]
Note that have fixed this issue our maintained fork: https://github.com/wikimedia/eslint-plugin-no-jquery/blob/master/rules/utils.js#L32

**Comment by KovalenkoStas** [comment]
@edg2s Thank you! We will check it out!
