### ISSUE TITLE
How about adding support for deprecated jQuery methods ?

### ISSUE THREAD

**Issue by wyvernnot** [dgraham/eslint-plugin-jquery#4]
Recently, I was fixing bugs during migration jQuery to 3.x .

And I found that `$(elem).size()` has been deprecated and removed in  [1.8](http://api.jquery.com/category/deprecated/deprecated-1.8/)

What if this plugin supports checking deprecated jQuery methods

@gibson042 @mgol

**Comment by dgraham** [comment]
A pull request that adds a rule for `size`, suggesting `length` instead, is welcome.
