### ISSUE TITLE
rules/no-data: Prefer WeakMap to $.data

### ISSUE THREAD

**Issue by dbarnespaychex** [dgraham/eslint-plugin-jquery#7]
Just wondering: why encourage WeakMap instead of [HTMLElement.dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset)?

**Comment by dgraham** [comment]
The `dataset` API lets you store string keys and values in an element's `data-` attributes. A WeakMap allows arbitrary objects to be associated with an element by using the element itself as the key.

```js
const data = new WeakMap()
data.set(element, new Date())
```

When the element is removed from the tree and garbage collected, the weak reference inside the map is cleared too.
